apiVersion: batch/v1
kind: Job
metadata:
  name: post-sync-job
  annotations:
    argocd.argoproj.io/hook: PostSync
    # argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
      - name: wxwork-notification
        image: curlimages/curl
        command:
          - "curl"
          - "--request"
          - "POST"
          - "https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=0183dd7f-4e48-4c91-9598-88c18fcd9e12"
          - "--header"
          - "'Content-Type: application/json'"
          - "--data-raw"
          - "{\"msgtype\": \"text\",\"text\": {\"content\": \"任务同步完成\"}}"
      restartPolicy: Never
  backoffLimit: 1
