apiVersion: batch/v1
kind: Job
metadata:
  name: sync-job
  annotations:
    argocd.argoproj.io/hook: Sync
    # argocd.argoproj.io/hook-delete-policy: HookFailed
spec:
  # ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
      - name: syncing
        image: alpine:latest
        command: ["echo",  "资源同步中"]
      restartPolicy: Never
